
// Login and logout operations
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAILED = 'AUTH_FAILED'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const RESET_GLOBAL_ERROR_MSG = 'RESET_GLOBAL_ERROR_MSG'

// Upload similar data (Students or Subjects data)
export const UPLOAD_START = 'UPLOAD_START'
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS'
export const UPLOAD_FAILED = 'UPLOAD_FAILED'
export const RESET_CONFIRMATION_MSG = 'RESET_CONFIRMATION_MSG'

// Fetch, Delete, Edit, and Search Students
export const FETCH_STUDENTS_START = 'FETCH_STUDENTS_START'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENTS_FAILED = 'FETCH_STUDENTS_FAILED'

export const DELETE_STUDENTS_START = 'DELETE_STUDENTS_START'
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS'
export const DELETE_STUDENTS_FAILED = 'DELETE_STUDENTS_FAILED'

export const SEARCH_STUDENTS = 'SEARCH_STUDENTS'

export const EDIT_STUDENTS_START = 'EDIT_STUDENTS_START'
export const EDIT_STUDENTS_SUCCESS = 'EDIT_STUDENTS_SUCCESS'
export const EDIT_STUDENTS_FAILED = 'EDIT_STUDENTS_FAILED'

// Fetch, Delete, Edit, and Search Subjects
export const FETCH_SUBJECTS_START = 'FETCH_SUBJECTS_START'
export const FETCH_SUBJECTS_SUCCESS = 'FETCH_SUBJECTS_SUCCESS'
export const FETCH_SUBJECTS_FAILED = 'FETCH_SUBJECTS_FAILED'

export const DELETE_SUBJECTS_START = 'DELETE_SUBJECTS_START'
export const DELETE_SUBJECTS_SUCCESS = 'DELETE_SUBJECTS_SUCCESS'
export const DELETE_SUBJECTS_FAILED = 'DELETE_SUBJECTS_FAILED'

export const SEARCH_SUBJECTS = 'SEARCH_SUBJECTS'

export const EDIT_SUBJECTS_START = 'EDIT_SUBJECTS_START'
export const EDIT_SUBJECTS_SUCCESS = 'EDIT_SUBJECTS_SUCCESS'
export const EDIT_SUBJECTS_FAILED = 'EDIT_SUBJECTS_FAILED'

// Fetch, Delete, Edit, and Search Subjects
export const FETCH_LOCATIONS_START = 'FETCH_LOCATIONS_START'
export const FETCH_LOCATIONS_SUCCESS = 'FETCH_LOCATIONS_SUCCESS'
export const FETCH_LOCATIONS_FAILED = 'FETCH_LOCATIONS_FAILED'

export const DELETE_LOCATIONS_START = 'DELETE_LOCATIONS_START'
export const DELETE_LOCATIONS_SUCCESS = 'DELETE_LOCATIONS_SUCCESS'
export const DELETE_LOCATIONS_FAILED = 'DELETE_LOCATIONS_FAILED'

export const SEARCH_LOCATIONS = 'SEARCH_LOCATIONS'

export const EDIT_LOCATIONS_START = 'EDIT_LOCATIONS_START'
export const EDIT_LOCATIONS_SUCCESS = 'EDIT_LOCATIONS_SUCCESS'
export const EDIT_LOCATIONS_FAILED = 'EDIT_LOCATIONS_FAILED'

// Fetch, Add, Delete, Edit, and Search Dates

export const ADD_DATE_START = 'ADD_DATE_START'
export const ADD_DATE_SUCCESS = 'ADD_DATE_SUCCESS'
export const ADD_DATE_FAILED = 'ADD_DATE_FAILED'
export const RESET_ADD_DATE_MSG = 'RESET_ADD_DATE_MSG'

export const FETCH_DATES_START = 'FETCH_DATES_START'
export const FETCH_DATES_SUCCESS = 'FETCH_DATES_SUCCESS'
export const FETCH_DATES_FAILED = 'FETCH_DATES_FAILED'

export const DELETE_DATE_START = 'DELETE_DATE_START'
export const DELETE_DATE_SUCCESS = 'DELETE_DATE_SUCCESS'
export const DELETE_DATE_FAILED = 'DELETE_DATE_FAILED'

export const EDIT_DATE_START = 'EDIT_DATE_START'
export const EDIT_DATE_SUCCESS = 'EDIT_DATE_SUCCESS'
export const EDIT_DATE_FAILED = 'EDIT_DATE_FAILED'

export const SEARCH_DATES =  'SEARCH_DATES'